name: Researcher

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lit-review:
    if: startsWith(github.head_ref, 'lit-review/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetches entire git history

      - name: Literature Review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "60"
          direct_prompt: |
            You are a research assistant following CS197 methodology. 
            Focus on comprehensive paper review using Arxiv. Use git to review what has been done in the past. 
          mcp_config: |
            {
              "mcpServers": {
                "search": {
                  "command": "npx",
                  "args": ["-y", "mcp-remote", "https://mcp.exa.ai/mcp?exaApiKey=${{ secrets.EXA_API_KEY }}"]
                },
                "git": {
                  "command": "uvx",
                  "args": ["mcp-server-git"]
                }
              }
            }
          allowed_tools: "mcp__search__web_search_exa,mcp__git__git_log,mcp__git__git_show"
